site_name: Linear Algebra Pero Tagalog
site_description: Pero Tagalog
site_author: RM Villa

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - search.highlight

extra_css:
  - style.css

markdown_extensions:
  - pymdownx.arithmatex

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search